name: Maxwell Productions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3620072
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Maxwell Productions | Life's an Adventure Waiting to be Took"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.176409977953881
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
